#travis config file

sudo: required

services:
  - docker

before-install:
  - docker build -t prabudasv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -t prabudasv/docker-react npm run test
